import Footer from './components/footer'
import Header from './components/header'
import './globals.css'
import { Inter, Kanit } from 'next/font/google'

const kanit = Kanit({
  weight: ['300', '400'],
  subsets: ['latin'],
  display: 'swap',
})

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={kanit.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
